import React from "react";
import type { AIInterpretation } from "../../types/sentinel";
import { RiskLevelBadge, ConfidenceBar } from "./StatusBadge";

const LABEL: React.CSSProperties = {
  fontSize: 11,
  fontWeight: 700,
  textTransform: "uppercase",
  letterSpacing: "0.07em",
  color: "#9ca3af",
  marginBottom: 3,
};

function formatDate(iso: string) {
  return new Date(iso).toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

function isStale(stale_after: string | null): boolean {
  if (!stale_after) return false;
  return new Date(stale_after) < new Date();
}

interface TimelineCardProps {
  interp: AIInterpretation;
  isLatest: boolean;
}

function TimelineCard({ interp, isLatest }: TimelineCardProps) {
  const stale      = isStale(interp.stale_after);
  const invalidated = !interp.is_active && interp.invalidated_at !== null;
  const accentColor = invalidated ? "#9ca3af" : isLatest ? "#2563eb" : "#e5e7eb";

  let stateLabel = "Active";
  let stateBg    = "#f0fdf4";
  let stateColor = "#15803d";
  if (invalidated) { stateLabel = "Invalidated"; stateBg = "#f9fafb"; stateColor = "#6b7280"; }
  else if (stale)  { stateLabel = "Stale";       stateBg = "#fffbeb"; stateColor = "#92400e"; }

  return (
    <div
      data-testid="timeline-card"
      style={{
        background: "#fff",
        border: "1px solid #e5e7eb",
        borderLeft: `4px solid ${accentColor}`,
        borderRadius: 10,
        padding: "16px 20px",
        opacity: invalidated ? 0.75 : 1,
      }}
    >
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 }}>
        <div>
          <div style={{ fontWeight: 700, fontSize: 14, color: "#111827" }}>
            v{interp.interpretation_version} · {interp.dimension}
            {isLatest && (
              <span style={{
                marginLeft: 8, fontSize: 10, fontWeight: 700, padding: "2px 8px",
                borderRadius: 10, background: "#eff6ff", color: "#1d4ed8",
              }}>
                LATEST
              </span>
            )}
          </div>
          <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 2 }}>
            #{interp.id} · generated by {interp.generated_by}
            {interp.model_name && <> ({interp.model_name})</>}
          </div>
        </div>
        <span style={{
          fontSize: 11, fontWeight: 700, padding: "3px 10px",
          borderRadius: 20, background: stateBg, color: stateColor,
        }}>
          {stateLabel}
        </span>
      </div>

      {/* Risk + confidence */}
      <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: 16, marginBottom: 10, alignItems: "center" }}>
        <RiskLevelBadge level={interp.risk_level} />
        <ConfidenceBar value={interp.confidence} />
      </div>

      {/* Summary */}
      <div style={{ fontSize: 13, color: "#374151", lineHeight: 1.6, marginBottom: 10 }}>
        {interp.summary}
      </div>

      {/* Invalidation reason */}
      {invalidated && interp.invalidation_reason && (
        <div style={{
          background: "#f9fafb", border: "1px solid #e5e7eb",
          borderRadius: 6, padding: "8px 12px", marginBottom: 10,
        }}>
          <div style={LABEL}>Invalidation Reason</div>
          <div style={{ fontSize: 12, color: "#6b7280" }}>{interp.invalidation_reason}</div>
        </div>
      )}

      {/* Timestamps */}
      <div style={{ fontSize: 11, color: "#9ca3af", display: "flex", gap: 16, flexWrap: "wrap" }}>
        <span>Created {formatDate(interp.created_at)}</span>
        {interp.invalidated_at && (
          <span style={{ color: "#6b7280" }}>Invalidated {formatDate(interp.invalidated_at)}</span>
        )}
        {interp.stale_after && (
          <span style={{ color: stale ? "#b45309" : "#9ca3af" }}>
            {stale ? "Stale since" : "Fresh until"} {formatDate(interp.stale_after)}
          </span>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Public component
// ---------------------------------------------------------------------------

interface InterpretationTimelineProps {
  history: AIInterpretation[];
  loading: boolean;
  error?: string;
  entityId: string;
}

export function InterpretationTimeline({ history, loading, error, entityId }: InterpretationTimelineProps) {
  if (loading) {
    return (
      <div style={{ textAlign: "center", padding: "32px 0", color: "#9ca3af", fontSize: 13 }}>
        Loading timeline for {entityId}...
      </div>
    );
  }
  if (error) {
    return (
      <div style={{
        background: "#fef2f2", border: "1px solid #fca5a5",
        borderLeft: "4px solid #dc2626", borderRadius: 8, padding: "12px 16px",
      }}>
        <div style={{ fontWeight: 700, fontSize: 13, color: "#b91c1c" }}>Failed to load timeline</div>
        <div style={{ fontSize: 12, color: "#7f1d1d" }}>{error}</div>
      </div>
    );
  }
  if (history.length === 0) {
    return (
      <div style={{ textAlign: "center", padding: "48px 0", color: "#9ca3af" }}>
        <div style={{ fontSize: 28, marginBottom: 8 }}>○</div>
        <div style={{ fontSize: 14, fontWeight: 600, color: "#6b7280" }}>No interpretation history</div>
        <div style={{ fontSize: 13, marginTop: 4 }}>
          Run an orchestration evaluation for {entityId} to populate this timeline.
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Legend */}
      <div style={{ display: "flex", gap: 16, marginBottom: 16, fontSize: 12, color: "#6b7280", flexWrap: "wrap" }}>
        <span><span style={{ color: "#2563eb" }}>▌</span> Active (latest)</span>
        <span><span style={{ color: "#9ca3af" }}>▌</span> Invalidated</span>
        <span style={{ color: "#92400e" }}>⚠ Stale = past stale_after date</span>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        {history.map((interp, idx) => (
          <TimelineCard key={interp.id} interp={interp} isLatest={idx === 0 && interp.is_active} />
        ))}
      </div>
    </div>
  );
}
